### ISSUE TITLE
Question: Tests are failing without linkFramework("CoreFoundation")

### ISSUE THREAD

**Issue by mifopen** [mitchellh/zig-objc#2]
Hey! I'm new to Zig and system programming and macOS development and just wanted to clarify for myself one thing. Maybe you can help me with that.

What do you think could be a reason for some tests failing for me without providing `tests.linkFramework("CoreFoundation")` in the `build.zig`? In particular, there is no `className` property on `NSObject` class for me without the CoreFoundation linked.
Another symptom of potentially the same problem is the fact that even if I link CoreFoundation explicitly, I still have one test failing: class.zig / copyPropertyList. I definitely have less than 20 props in the class without any framework linked.

**Comment by mitchellh** [comment]
Thanks!
